name: Build and Deploy
on:
  push:
    branches:
      - main # Replace 'main' with the name of your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # Use v2 instead of v3 if you need to set persist-credentials to false.
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x' # Use a version of Node.js that is compatible with your project.
      
      - name: Install Dependencies ğŸ”§
        run: npm install # Replace with the command to install your project's dependencies.
      
      - name: Build Project ğŸ”¨
        run: npm run build # Replace with the command to build your project.
      
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0 # Use the latest version of the action.
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }} # Replace with your personal access token.
          branch: gh-pages # Replace with the name of the branch you want to deploy to.
          folder: build # Replace with the name of the folder you want to deploy.
          clean: true # Automatically remove deleted files from the deploy branch.
